[package]
name = "great_calculator"
version = "0.1.0"
edition = "2021"
opt-level = 3
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
indexmap = "2.2.6"